apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      server_name _;  

      location / {
        proxy_pass http://api-service:3000;  
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }
    }
