FROM mysql:8

ENV MYSQL_ROOT_PASSWORD=12345678
ENV MYSQL_DATABASE=mydb

COPY ./init.sql /docker-entrypoint-initdb.d/

# docker build -t mysql-rest-api .
# docker run -d -p 3306:3306 --name mysql-container2 mysql-rest-api
